spring:
  datasource:
    url: jdbc:mysql://localhost:3306/control_bac_system
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  servlet:
    context-path: /dev-api
