spring:
  datasource:
    url: jdbc:mysql://rm-2vcg83ybq4f2k1prxoo.mysql.cn-chengdu.rds.aliyuncs.com:3306/control_bac_system
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: bhsf234nhs@A
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  servlet:
    context-path: /dev-api